apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ex2-job
  namespace: ex2
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            command:
            - sh
            - -c
            - exit $((RANDOM % 2))
          restartPolicy: Never
