---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex4-deploy
  namespace: ex4
spec:
  selector:
    matchLabels:
      run: nginx
  replicas: 3
  strategy:
    #type: Recreate
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 3
      maxSurge: 0
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
