apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: ex6
  labels:
    app: ex6
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: memcached
  namespace: ex6
spec:
  containers:
  - name: memcached
    image: memcached
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: "kubernetes.io/hostname"
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - ex6        
---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: ex6
spec:
  containers:
  - name: redis
    image: redis
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: "kubernetes.io/hostname"
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - ex6        
---
apiVersion: v1
kind: Pod
metadata:
  name: httpd
  namespace: ex6
spec:
  containers:
  - name: httpd
    image: httpd
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: "kubernetes.io/hostname"
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - ex6        

